---
- name: Create service group for Celery
  user: name="{{ celery_user_group }}"
        system=yes
        state=present

- name: Create service account for Celery
  user: name="{{ celery_user }}"
        group="{{ celery_user_group }}"
        system=yes
        home="{{ celery_dir }}"
        shell=/bin/false
        state=present

- name: Install Celery
  pip: name="celery[redis]" version="{{ celery_version }}" state=present

- name: Configure Celery service definition
  template: src=celery.conf.j2 dest=/etc/init/celery.conf
  notify:
    - Restart Celery

- name: Touch log file if it does not exist
  copy: content="" dest="{{ celery_log }}" force=no

- name: Set log file permissions
  file: path="{{ celery_log }}" owner="{{ celery_user }}" group="{{ celery_user_group }}" mode=0644

- name: Configure Celery log rotation
  template: src=logrotate_celery.j2 dest=/etc/logrotate.d/celery
